MMS.StoreFulfillment.ManagerUI/Models/RequestView/CustomerViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MMS.StoreFulfillment.ManagerUI.Models.RequestView
{
    public class CustomerViewModel
    {
        [Display(Name = "Фамилия")]
        public string CustomerSurname { get; set; }
        [Display(Name = "Имя")]
        public string CustomerName { get; set; }
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Display(Name = "Телефон")]
        public string Phone { get; set; }
    }
}

MMS.StoreFulfillment.ManagerUI/Models/RequestView/DeliveryViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MMS.StoreFulfillment.ManagerUI.Models.RequestView
{
    public class DeliveryViewModel
    {
        [Display(Name = "Тип доставки")]
        public bool HasDelivery { get; set; }
        [Display(Name="Магазин")]
        public string SapCode { get; set; }
    }
}

MMS.StoreFulfillment.ManagerUI/Models/RequestView/Extensions.cs
using System.Linq;
using MMS.StoreFulfillment.Entities.SF.Items;
using MMS.StoreFulfillment.ManagerUI.Models.ManagerTask;

namespace MMS.StoreFulfillment.ManagerUI.Models.RequestView
{
    public static class Extensions
    {
        public static RequestViewModel ToRequestViewModel(this ItemsMovementRequest request)
        {
            return new RequestViewModel
            {
                OrderId = request.CustomerOrder.CustomerOrderId,
                Items = request.Items.Select(t => new ItemViewModel(t)).ToList(),
                CustomerInfo = new CustomerViewModel
                {
                    CustomerName = request.Contact.FirstName,
                    CustomerSurname = request.Contact.LastName,
                    Email = request.Contact.Email,
                    Phone = request.Contact.Phone
                },
                DeliveryInfo = new DeliveryViewModel
                {
                    HasDelivery = request.CustomerOrder.DeliveryType == DeliveryType.Delivery,
                    SapCode = request.SapCode,
                },
                WWSOrderId = request.WwsOrderId
            };
        }
    }
}

MMS.StoreFulfillment.ManagerUI/Models/RequestView/RequestViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using MMS.StoreFulfillment.ManagerUI.Models.ManagerTask;

namespace MMS.StoreFulfillment.ManagerUI.Models.RequestView
{
    public class RequestViewModel
    {
        [Display(Name = "Номер заказа")]
        public string OrderId { get; set; }
        [Display(Name = "Номер резерва")]
        public string WWSOrderId { get; set; }

        [UIHint("ItemViewModel")]
        public List<ItemViewModel> Items { get; set; }

        [UIHint("CustomerViewModel")]
        public CustomerViewModel CustomerInfo { get; set; }

        [UIHint("DeliveryViewModel")]
        public DeliveryViewModel DeliveryInfo { get; set; }

        [Display(Name = "Суммарно")]
        public decimal TotalPrice
        {
            get { return Items.Sum(t => t.Price * t.Qty); }
        }
    }
}

MMS.StoreFulfillment.ManagerUI/Controllers/RequestViewController.cs
using System;
using System.Linq.Expressions;
using System.Web.Mvc;
using MMS.StoreFulfillment.Entities.SF.Items;
using MMS.StoreFulfillment.ManagerUI.Models.RequestView;

namespace MMS.StoreFulfillment.ManagerUI.Controllers
{
    public class RequestViewController : Controller
    {
        private readonly IStoreFulfillmentStorage _storeFulfillmentStorage;

        public RequestViewController(IStoreFulfillmentStorage storeFulfillmentStorage)
        {
            _storeFulfillmentStorage = storeFulfillmentStorage;
        }

        public ActionResult Index(string requestId)
        {
            var request = _storeFulfillmentStorage.GetById(requestId,
                new Expression<Func<ItemsMovementRequest, object>>[] { t => t.Items });

            var requestViewModel = request.ToRequestViewModel();

            return View(requestViewModel);
        }
    }
}

MMS.StoreFulfillment.ManagerUI/Views/RequestView/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = null;
}

@Styles.Render("~/Content/managerCss")
@using MMS.StoreFulfillment.ManagerUI.Common
@model MMS.StoreFulfillment.ManagerUI.Models.RequestView.RequestViewModel
<div style="min-width: 450px;">
    @using (Html.BeginForm("Index", "RequestView", FormMethod.Post, new {@class = "form-horizontal"}))
    {
        <fieldset>
            <h4>Заказ</h4>
            <div class="form-group display">
                @Html.LabelFor(m => m.OrderId, new { @class = "col-sm-2 control-label" })
                <div class="col-sm-10">
                    <div class="form-control-static">@Model.OrderId</div>
                </div>
            </div>
            @if (!string.IsNullOrEmpty(Model.WWSOrderId))
            {
                <div class="form-group display">
                    @Html.LabelFor(m => m.WWSOrderId, new { @class = "col-sm-2 control-label" })
                    <div class="col-sm-10">
                        <div class="form-control-static">@Model.WWSOrderId</div>
                    </div>
                </div>
            }

            <h4>Корзина</h4>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <td>Позиция</td>
                        <td>Артикул</td>
                        <td>Наименование</td>
                        <td>Количество</td>
                        <td>Цена</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @Html.DisplayForCollection(m => m.Items)
                    <tr>
                        <td colspan="3"></td>
                        <td style="font-weight: bold;">Итого</td>
                        <td style="font-weight: bold;">@Html.DisplayFor(m => m.TotalPrice) руб.</td>
                        <td></td>
                    </tr>
                </tbody>
            </table>

        </fieldset>
        <fieldset>
            @Html.DisplayFor(m => m.DeliveryInfo)
            @Html.DisplayFor(m => m.CustomerInfo)
        </fieldset>
    }
</div>